### ISSUE TITLE
Error after building and running for the first time 

### ISSUE THREAD

**Issue by DiegoMoussallem** [DeFacto/DeFacto#33]
Hi, 

I followed the steps and I couldn't make it run. The error is the following: 

```Sending build context to Docker daemon  207.1MB
Step 1/29 : FROM rawmind/alpine-jdk8:1.8.181-0
 ---> f4158f2295dd
Step 2/29 : maintainer rameshkjes@gmail.com
 ---> Using cache
 ---> 7b0c5b45b751
Step 3/29 : RUN apk add --no-cache curl
 ---> Using cache
 ---> f36e12eaaac0
Step 4/29 : ENV MAVEN_VERSION 3.5.2
 ---> Using cache
 ---> 1a186fe01140
Step 5/29 : RUN mkdir -p /usr/share/maven   && curl -fsSL http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz     | tar -xzC /usr/share/maven --strip-components=1   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
 ---> Using cache
 ---> 42fd1938dea5
Step 6/29 : ENV MAVEN_HOME /usr/share/maven
 ---> Using cache
 ---> 025a8b3255f9
Step 7/29 : RUN set MAVEN_OPTS= -Dfile.encoding=UTF-8
 ---> Using cache
 ---> bae694a5d3e8
Step 8/29 : RUN apk add --no-cache git
 ---> Using cache
 ---> 1dbecf490f4c
Step 9/29 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> e556cd7fc061
Step 10/29 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 006a75781444
Step 11/29 : RUN git clone https://github.com/DeFacto/DeFacto.git
 ---> Using cache
 ---> f090d9de106e
Step 12/29 : WORKDIR /usr/src/app/DeFacto
 ---> Using cache
 ---> 78a7530a81e1
Step 13/29 : RUN git checkout defacto-docker
 ---> Using cache
 ---> e1a740bfbdf8
Step 14/29 : RUN sed "2s#/home/user/Repos/DeFacto/data/#/usr/src/app/DeFacto/data/#g" -i defacto-core/src/main/resources/defacto.ini
 ---> Using cache
 ---> 7bcd8dc66fbf
Step 15/29 : RUN sed "36s#/home/user/Repos/DeFacto/data/crawl_repo#/usr/src/app/DeFacto/data/crawl_repo#g" -i defacto-core/src/main/resources/defacto.ini
 ---> Using cache
 ---> ccbb7f97758d
Step 16/29 : RUN sed "92s#/home/user/Repos/DeFacto/data/wordnet/dict#/usr/src/app/DeFacto/data/wordnet/dict#g" -i defacto-core/src/main/resources/defacto.ini
 ---> Using cache
 ---> e329bd66cb8a
Step 17/29 : RUN mvn clean install
 ---> Using cache
 ---> cb5b3042c4b1
Step 18/29 : WORKDIR /usr/src/app/DeFacto/defacto-restful
 ---> Using cache
 ---> 276d1b7f5261
Step 19/29 : RUN mvn clean install
 ---> Using cache
 ---> 5fdfdf977191
Step 20/29 : ARG google_api_key_client_id_variable=default_value
 ---> Using cache
 ---> 9a8d5abfe542
Step 21/29 : ARG google_api_key_secret_variable=default_value
 ---> Using cache
 ---> 8cd5c3cb810e
Step 22/29 : ENV google_api_key_client_id=$google_api_key_client_id_variable
 ---> Using cache
 ---> 7089d8fb44c2
Step 23/29 : ENV google_api_key_secret=$google_api_key_secret_variable
 ---> Using cache
 ---> dc2a624e758b
Step 24/29 : RUN sed "33s#dummy#$google_api_key_client_id#g" -i src/main/resources/application.yml
 ---> Using cache
 ---> dbc39c56bc41
Step 25/29 : RUN sed "34s#dummy#$google_api_key_secret#g" -i src/main/resources/application.yml
 ---> Using cache
 ---> c716f1671935
Step 26/29 : VOLUME root/.m2
 ---> Using cache
 ---> 72500f1b5b85
Step 27/29 : RUN export MAVEN_OPTS=-Xmx4G
 ---> Using cache
 ---> 610d7765c132
Step 28/29 : CMD ["-Dexec.mainClass=org.aksw.defacto.restful.App"]
 ---> Using cache
 ---> 39f83e77d21a
Step 29/29 : ENTRYPOINT ["mvn", "compile", "exec:java"]
 ---> Using cache
 ---> f625d0ab3e4f
Successfully built f625d0ab3e4f
Successfully tagged defacto_git:latest
Diegos-MacBook-Pro:docker diegomoussallem$ docker run -p 4441:4441 defacto_git .
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.aksw:defacto-restful:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-starter-web:jar -> duplicate declaration of version (?) @ org.aksw:defacto-restful:[unknown-version], /usr/src/app/DeFacto/defacto-restful/pom.xml, line 79, column 15
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ org.aksw:defacto-restful:[unknown-version], /usr/src/app/DeFacto/defacto-restful/pom.xml, line 135, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
Downloading from spring-releases: https://repo.spring.io/libs-release/org/springframework/boot/spring-boot-maven-plugin/maven-metadata.xml
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/springframework/boot/spring-boot-maven-plugin/maven-metadata.xml (3.4 kB at 4.7 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom (5.6 kB at 19 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.jar (27 kB at 89 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom (21 kB at 67 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.jar (124 kB at 303 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (4.7 kB at 14 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom (12 kB at 44 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/maven-parent/9/maven-parent-9.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/maven-parent/9/maven-parent-9.pom (33 kB at 112 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/apache/4/apache-4.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/apache/4/apache-4.pom (0 B at 0 B/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar (24 kB at 73 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 kB at 43 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (13 kB at 48 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/maven-parent/15/maven-parent-15.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/maven-parent/15/maven-parent-15.pom (24 kB at 86 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/apache/6/apache-6.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/apache/6/apache-6.pom (0 B at 0 B/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (209 kB at 405 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom (11 kB at 44 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar (153 kB at 387 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom (9.3 kB at 34 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/release/maven-release/2.3.2/maven-release-2.3.2.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/release/maven-release/2.3.2/maven-release-2.3.2.pom (8.6 kB at 33 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.jar (44 kB at 162 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 106 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 66 kB/s)
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/apache/maven/plugins/maven-metadata.xml (19 kB at 36 kB/s)
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/maven-metadata.xml (27 kB at 51 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (741 B at 12 kB/s)
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (768 B at 1.3 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom (13 kB at 46 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom (34 kB at 77 kB/s)
Downloading from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar
Downloaded from spring-releases: https://repo.spring.io/libs-release/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar (58 kB at 203 kB/s)
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building defacto-restful 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.413 s
[INFO] Finished at: 2019-03-21T18:20:17Z
[INFO] Final Memory: 13M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
Diegos-MacBook-Pro:docker diegomoussallem$ ```

**Comment by DiegoMoussallem** [comment]
After cleaning, I got to make it run. Interesting that I had to remove the punctuation in the end of ```docker run -p 4441:4441 defacto_git .```

**Comment by DiegoMoussallem** [comment]
But, apart from the examples, nothing is working. it is returning 400 Bad Request
Wrong input.

**Comment by DiegoMoussallem** [comment]
it seems to be something related to Azure

```20:15:39 DEBUG [pool-13-thread-29] - [BasicClientConnectionManager]- Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@5fe3caf7
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:532)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at net.billylieurance.azuresearch.AbstractAzureSearchQuery.doQuery(AbstractAzureSearchQuery.java:337)
	at org.aksw.defacto.search.engine.bing.AzureBingSearchEngine.query(AzureBingSearchEngine.java:107)
	at org.aksw.defacto.search.engine.DefaultSearchEngine.getSearchResults(DefaultSearchEngine.java:40)
	at org.aksw.defacto.search.crawl.SearchResultCallable.call(SearchResultCallable.java:35)
	at org.aksw.defacto.search.crawl.SearchResultCallable.call(SearchResultCallable.java:19)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at org.aksw.defacto.search.engine.bing.AzureBingSearchEngine.query(AzureBingSearchEngine.java:114)
	at org.aksw.defacto.search.engine.DefaultSearchEngine.getSearchResults(DefaultSearchEngine.java:40)
	at org.aksw.defacto.search.crawl.SearchResultCallable.call(SearchResultCallable.java:35)
	at org.aksw.defacto.search.crawl.SearchResultCallable.call(SearchResultCallable.java:19)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:15:45 DEBUG [cluster-ClusterId{value='5c93ed1446e0fb0001b39cea', description='null'}-localhost:27017] - [connection]- Closing connection connectionId{localValue:199}
20:15:46 DEBUG [cluster-ClusterId{value='5c93ed1446e0fb0001b39ceb', description='null'}-localhost:27017] - [connection]- Closing connection connectionId{localValue:200}```

**Comment by diegoesteves** [comment]
Hello @DiegoMoussallem, yes you need to register at Microsoft Azure to obtain an API. In the next release, we will change the interface to support other databases, in general (e.g., babetnet). Please let me know if that has fixed the issue :-)
